In [1]:
cd /mnt/Data/Scripts/Sleep-Oct14/src/

/mnt/Data/Scripts/Sleep-Oct14/src


In [2]:
%matplotlib
%load_ext autoreload
%autoreload 2
import numpy as np
import matplotlib.pyplot as pl
import pickle as pkl
import random
import os,sys
import scipy.signal as scsig

Using matplotlib backend: Qt4Agg


In [4]:
extraPaths=["/home/chenani/pypacks/lib/python2.7/site-packages",
    "/home/chenani/ATLAS-clone/workspace/NeuNeuro/src/scripts/",
    "/home/haas/.local/lib/"]
for p in extraPaths:
    if not sys.path.count(p):
        sys.path.insert(1, p)


In [ ]:
import Recordings
import signale, trajectory, custom_plot

In [ ]:
colors = ['#FF0000', '#0000FF', '#008000', '#00FFFF', '#FF00FF', '#EE82EE',
        '#808000', '#800080', '#FF6347', '#FFFF00', '#9ACD32', '#4B0082',
        '#FFFACD', '#C0C0C0', '#A0522D', '#FA8072', '#FFEFD5', '#E6E6FA',
        '#F1FAC1', '#C5C5C5', '#A152ED', '#FADD72', '#F0EFD0', '#EEE6FF',
        '#01FAC1', '#F5F5F5', '#A152FF', '#FAFD72', '#F0EFDF', '#EEEFFF',
        '#F1FA99', '#C9C9C9', '#A152DD', '#FA5572', '#FFFFD0', '#EDD6FF']
pretty_colors_set1 = [(0.8941176470588236, 0.10196078431372549, 0.10980392156862745),
 (0.21568627450980393, 0.49411764705882355, 0.7215686274509804),
 (0.30196078431372547, 0.6862745098039216, 0.2901960784313726),
 (0.596078431372549, 0.3058823529411765, 0.6392156862745098),
 (1.0, 0.4980392156862745, 0.0),
 (1.0, 1.0, 0.2),
 (0.6509803921568628, 0.33725490196078434, 0.1568627450980392),
 (0.9686274509803922, 0.5058823529411764, 0.7490196078431373),
 (0.6, 0.6, 0.6)]

pretty_colors_set2 = [(0.4, 0.7607843137254902, 0.6470588235294118),
 (0.9882352941176471, 0.5529411764705883, 0.3843137254901961),
 (0.5529411764705883, 0.6274509803921569, 0.796078431372549),
 (0.9058823529411765, 0.5411764705882353, 0.7647058823529411),
 (0.6509803921568628, 0.8470588235294118, 0.32941176470588235),
 (1.0, 0.8509803921568627, 0.1843137254901961),
 (0.8980392156862745, 0.7686274509803922, 0.5803921568627451),
 (0.7019607843137254, 0.7019607843137254, 0.7019607843137254)]
grey = np.ones(3) * .25
transred = '#FFA1A1'

In [ ]:
trajFile = '/home/chenani/dataWork/ali/MECLesion_SleepData/Marta/Rat3656/LinearTrack_03-03-2015_Day1/parrentData/linearTrack_Trajectory.traj'
placeCellList = '/home/chenani/dataWork/ali/MECLesion_SleepData/Marta/Rat3656/LinearTrack_03-03-2015_Day1/parrentData/placeCells.spk'

In [11]:
plzList = pkl.load(open(placeCellList,'rb'))
traj = pkl.load(open(trajFile,'rb'))

ImportError: No module named NeuroTools.signals

In [13]:
speed = traj.getSpeed()
pl.plot(speed[0],speed[1])
traj.threshspeed = 0.8
traj.getLeftAndRightwardRuns()

NOTE: Need to calculate running trajectory.
calculating trajectory with running speed >= 0.8


In [14]:
(plzList.t_stop - plzList.t_start)/3600000

2.5120805555555554

In [15]:
for ii in range(len(plzList)):
    plzList[ii].tags = plzList.tags[ii].copy()

In [16]:
(traj.t_start*1000 - plzList.t_start)/3600000

1.0017772222222223

In [17]:
lt1List = plzList.time_slice(traj.t_start * 1000,traj.t_stop * 1000)

In [18]:
interNeuronIDs = np.int0([])
for jj,item in enumerate(plzList):
    if item.mean_rate() > 5.5:
        interNeuronIDs = np.append(interNeuronIDs,jj)
placeCellIDs = np.array([item for item in lt1List.id_list if item not in interNeuronIDs])
interNeuronIDs,placeCellIDs

(array([], dtype=int64),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]))

In [19]:
leftplz = np.int0([0,1,2,3,5,6,8,10,11,12])
rightplz = np.int0([0,1,2,3,5,6,10,11,12])

In [20]:
pl.plot(plzList.mean_rates())

In [21]:
lt1List._spikezugList__recalc_startstop()
lt1List.changeTimeUnit('s')

In [22]:
for item in lt1List:
    if item.t_stop > traj.t_stop * 1000:
        print item.t_stop

In [23]:
for zaehler, st in enumerate(lt1List):
    st.traj = traj
    st.getSpikePlaces()
    st.getRunningSpikes()
    st.getLeftAndRightwardSpikes(onlyRunning=True)
    

NOTE: Using linear interpolation to get the places.
NOTE: Using linear interpolation to get the places.
NOTE: Using linear interpolation to get the places.
NOTE: Using linear interpolation to get the places.
NOTE: Using linear interpolation to get the places.
NOTE: Using linear interpolation to get the places.
NOTE: Using linear interpolation to get the places.
NOTE: Using linear interpolation to get the places.
NOTE: Using linear interpolation to get the places.
NOTE: Using linear interpolation to get the places.
NOTE: Using linear interpolation to get the places.
NOTE: Using linear interpolation to get the places.
NOTE: Using linear interpolation to get the places.


/usr/local/bin/anaconda/lib/python2.7/site-packages/numpy/ma/core.py:2200: RuntimeWarning: invalid value encountered in less_equal
  condition = umath.less_equal(mabs(xnew - value), atol + rtol * mabs(value))


In [24]:
bins = np.linspace(0,2,80)
height = 0
idxL = leftplz#80p
idxR = rightplz#80p
peaksR = []
peaksL = []
hstSmoothR = []
hstSmoothL = []
fR,axarrR = pl.subplots(len(idxR),sharex=True,sharey=True)
fL,axarrL = pl.subplots(len(idxL),sharex=True,sharey=True)

for ii in range(len(idxR)):
    lt1List[idxR[ii]].getRunningSpikes(1.2)
    hstR = np.histogram(np.intersect1d(lt1List[idxR[ii]].run_spikePlaces[:,0],lt1List[idxR[ii]].rechts_spikePlaces[:,0]),bins)
    hstL = np.histogram(np.intersect1d(lt1List[idxR[ii]].run_spikePlaces[:,0],lt1List[idxR[ii]].links_spikePlaces[:,0]),bins)
    hstSmoothR.append(np.convolve(hstR[0],scsig.gaussian(20,4),'same'))
    hstSmoothL.append(np.convolve(hstL[0],scsig.gaussian(20,4),'same'))
    hstSmoothR[-1] /= float(hstSmoothR[-1].max())
    hstSmoothL[-1] /= float(hstSmoothL[-1].max())
    peaksR.append(bins[hstSmoothR[-1].argmax()])
    #peaksL.append(bins[hstSmoothL[-1].argmax()])

#peaksL = np.array(peaksL)
peaksR = np.array(peaksR)
plidxR = peaksR.argsort()
#plidxL = peaksL.argsort()
placeSortedR = idxR[plidxR]
#placeSortedL = idxR[plidxL]
for ii in range(placeSortedR.size):
    axarrR[ii].plot(bins[:-1],hstSmoothR[plidxR[ii]] + height,color=pretty_colors_set1[np.int0(np.math.fmod(ii,9))])
    axarrR[ii].plot(bins[:-1],hstSmoothL[plidxR[ii]] + height,color=colors[plidxR[ii]],dashes=(5,10))
    axarrR[ii].axvline(bins[hstSmoothR[plidxR[ii]].argmax()],0.05,0.95,color=pretty_colors_set1[np.int0(np.math.fmod(ii,9))])
    #axarr[ii].axvline(bins[hstSmoothL[plidxL[ii]].argmax()],0.79,0.95,color=colors[plidxL[ii]])
    axarrR[ii].set_ylabel(placeSortedR[ii])#spk.tags[idx[ii]]['file'][2:6])
    height += 0.0005
    pl.setp(axarrR[ii].get_yticklabels(), visible=False)

###############################LEFTWARDS FIELDS!
############################################################################
peaksR = []
peaksL = []
hstSmoothR = []
hstSmoothL = []
for ii in range(len(idxL)):
    lt1List[idxL[ii]].getRunningSpikes(1.2)
    hstR = np.histogram(np.intersect1d(lt1List[idxL[ii]].run_spikePlaces[:,0],lt1List[idxL[ii]].rechts_spikePlaces[:,0]),bins)
    hstL = np.histogram(np.intersect1d(lt1List[idxL[ii]].run_spikePlaces[:,0],lt1List[idxL[ii]].links_spikePlaces[:,0]),bins)
    hstSmoothR.append(np.convolve(hstR[0],scsig.gaussian(20,4),'same'))
    hstSmoothL.append(np.convolve(hstL[0],scsig.gaussian(20,4),'same'))
    hstSmoothR[-1] /= float(hstSmoothR[-1].max())
    hstSmoothL[-1] /= float(hstSmoothL[-1].max())
    #peaksR.append(bins[hstSmoothR[-1].argmax()])
    peaksL.append(bins[hstSmoothL[-1].argmax()])

peaksL = np.array(peaksL)
#peaksR = np.array(peaksR)
#plidxR = peaksR.argsort()
plidxL = peaksL.argsort()
#placeSortedR = idxL[plidxR]
placeSortedL = idxL[plidxL]
for ii in range(placeSortedL.size):
    axarrL[ii].plot(bins[:-1],hstSmoothL[plidxL[ii]] + height,color=pretty_colors_set1[np.int0(np.math.fmod(ii,9))])
    axarrL[ii].plot(bins[:-1],hstSmoothR[plidxL[ii]] + height,color=colors[plidxL[ii]],dashes=(5,10))
    axarrL[ii].axvline(bins[hstSmoothL[plidxL[ii]].argmax()],0.05,0.95,color=pretty_colors_set1[np.int0(np.math.fmod(ii,9))])
    #axarr[ii].axvline(bins[hstSmoothL[plidxL[ii]].argmax()],0.79,0.95,color=colors[plidxL[ii]])
    axarrL[ii].set_ylabel(placeSortedL[ii])#spk.tags[idx[ii]]['file'][2:6])
    height += 0.0005
    pl.setp(axarrL[ii].get_yticklabels(), visible=False)


NOTE: Reset threshspeed from 0.8 to 1.2 m/s
NOTE: Now calculating running traj > 1.2 m/s
calculating trajectory with running speed >= 1.2


In [25]:
placeSortedL,placeSortedR

(array([ 8, 10, 11,  3,  5,  6,  0, 12,  2,  1]),
 array([ 5,  1,  2,  3, 11,  0,  6, 10, 12]))

In [87]:
for ii,item in enumerate(placeSortedL):
    fname =  lt1List.tags[item]['file']
    if fname.find('TT7') ==0:
        print fname
        print item
print '********************'
for ii,item in enumerate(placeSortedR):
    fname =  lt1List.tags[item]['file']
    if fname.find('TT7') ==0:
        print fname
        print item

********************


In [91]:
idx = []
for jj,item in enumerate(lt1List):
    if hasattr(item,'run_spikePlaces'):
        n = item.run_spikePlaces.shape[0]
        nr = np.intersect1d(item.run_spikePlaces[:,0],item.rechts_spikePlaces[:,0]).size
        nl = np.intersect1d(item.run_spikePlaces[:,0],item.links_spikePlaces[:,0]).size
        if (n > 100 and n <19800):
            idx.append(jj)

In [92]:
#idx = np.array(right)
peaksR = []
f,axarr = pl.subplots(len(idx),sharex=True,sharey=True)
hstSmoothR = []

for ii in range(len(idx)):
    lt1List[idx[ii]].getRunningSpikes()
    hstR = np.histogram(np.intersect1d(lt1List[idx[ii]].run_spikePlaces[:,0],lt1List[idx[ii]].rechts_spikePlaces[:,0]),bins)
    hstSmoothR.append(np.convolve(hstR[0],scsig.gaussian(10,3),'same'))
    hstSmoothR[-1] /= float(hstSmoothR[-1].max())
    #hstSmoothL /= float(hstSmoothL.max())
    peaksR.append(bins[hstSmoothR[-1].argmax()])
    #if hstR[0].sum() > 10:
    axarr[ii].plot(bins[:-1],hstSmoothR[-1] + height,color=colors[ii])
    axarr[ii].axvline(bins[hstSmoothR[-1].argmax()],0.9,0.95,color=colors[ii])
    height += 0.0005
    axarr[ii].set_ylabel(idx[ii])#spk.tags[idx[ii]]['file'][2:6])
    pl.setp(axarr[ii].get_yticklabels(), visible=False)

peaksL = []
fL,axarrL = pl.subplots(len(idx),sharex=True,sharey=True)
hstSmoothL = []
for ii in range(len(idx)):
    lt1List[idx[ii]].getRunningSpikes()
    hstR = np.histogram(np.intersect1d(lt1List[idx[ii]].run_spikePlaces[:,0],lt1List[idx[ii]].links_spikePlaces[:,0]),bins)
    hstSmoothL.append(np.convolve(hstR[0],scsig.gaussian(10,3),'same'))
    hstSmoothL[-1] /= float(hstSmoothL[-1].max())
    peaksL.append(bins[hstSmoothR[-1].argmax()])
    axarrL[ii].plot(bins[:-1],hstSmoothL[-1] + height,color=colors[ii])
    axarrL[ii].axvline(bins[hstSmoothL[-1].argmax()],0.9,0.95,color=colors[ii])
    height += 0.0005
    axarrL[ii].set_ylabel(idx[ii])#spk.tags[idx[ii]]['file'][2:6])
    pl.setp(axarrL[ii].get_yticklabels(), visible=False)
pl.title('Left Fields')

In [93]:
pl.plot(zell.traj.run_times, zell.traj.run_places[:, 0], linewidth=2.5,color=grey)  # only run trajectory
pl.plot(zell.traj.times, zell.traj.places[:, 0], linewidth=.5, color='k')  # original/full trajectory
pl.plot(zell.spike_times, zell.spikePlaces[:, 0], marker='.', linestyle='None',color= transred)  # all spiketimes
pl.plot(zell.run_spikeTimes, zell.run_spikePlaces[:, 0], 'r.')  # only running-spikes


NameError: name 'zell' is not defined

In [285]:
pl.plot(zell.spike_times,zell.spikePlaces[:,0],'r.')

In [33]:
right80p = []
for item in right:
    hst = lt1List[item].time_histogram()
    if np.where(hst == 0)[0].size < 24:
        right80p.append(item)
leftt80p = []
for item in left:
    hst = lt1List[item].time_histogram()
    if np.where(hst == 0)[0].size < 24:
        leftt80p.append(item)
right80p = np.array(right80p)
leftt80p = np.array(leftt80p)

NameError: name 'right' is not defined

In [337]:
right80p.size,leftt80p.size

(39, 43)

-22.427700735040005

In [311]:
pl.plot(zell.time_histogram())