In [1]:
%matplotlib
%load_ext autoreload
%autoreload 2
import scipy.signal as scsig
import numpy as np
import matplotlib.pyplot as pl
import NeuroTools as NT
import NeuroTools.stgen as stgen
import pickle as pkl
import sets
import random

/home/aliche/anaconda3/envs/py27/lib/python2.7/site-packages/matplotlib/font_manager.py:281: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  'Matplotlib is building the font cache using fc-list. '


Using matplotlib backend: Qt5Agg


/home/aliche/anaconda3/envs/py27/lib/python2.7/site-packages/NeuroTools/analysis.py:34: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to u'Qt5Agg' by the following code:
  File "/home/aliche/anaconda3/envs/py27/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/aliche/anaconda3/envs/py27/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/aliche/anaconda3/envs/py27/lib/python2.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/aliche/anaconda3/envs/py27/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/aliche/anaconda3/envs/py27/lib/python2.7/site-packages

In [2]:
cd /home/aliche/ownCloud/Workspaces/Eclipse/dataAnalysis/Sleep-current/

/home/aliche/ownCloud/Workspaces/Eclipse/dataAnalysis/Sleep-current


In [6]:
%run ephys_loader.py /media/chenani/Data/ephysdata/Rats/MECLesion/Rat434Lesion/sleep6/sleep6.ephys

In [3]:
zug = stgen.StGen()

In [4]:
def subsequence(sub,ref):
    '''
    A function to determine the number of specefic sequence repeated within a larger sequence.
    
    Parameters:
    sub:
    ref:
    
    
    Returns:
    idx : This an array containing the index of elements of sub in the ref! if idx is stricktly increasing the sequence sub
    is replayed whithin sequence ref!
    '''
    ref = np.array(ref)
    idx = np.array([])
    for ii in range(len(sub)):
        index = np.where(ref == sub[ii])[0]
        if index.size:
            idx = np.append(idx,index)
        else: 
            return [] , False
    idx = np.int0(idx)
    return idx, True

In [5]:
### Detrmining the rate functions
error = []
rates = []
for item in rec.spikes:
    kernel,norm,m_idx = NT.analysis.make_kernel('GAU',100,0.5)
    rates.append(item.instantaneous_rate(0.5,kernel,norm,m_idx))
    error.append(100 * np.abs(rates[-1][1].mean() - item.mean_rate()) / item.mean_rate())
rates = np.array(rates)

NameError: name 'rec' is not defined

In [6]:
#### generating surrogate spike-trains with evaluated rates!
sq_stack = []
for ii in range(100):
    ID = -1
    surrogateTrains = signale.spikezugList(t_start=None, t_stop=None, dims=[2])
    for rate in rates:
        sp_train_dyn = zug.inh_poisson_generator(rate[1],rate[0],t_stop= rate[0][-1])
        ID += 1
        surrogateTrains.__setitem__(ID, sp_train_dyn)
        surrogateTrains.addTags(ID, generator='Inh Poisson',avg_rate=rate[1].mean(), file='cell '+ str(ID))
    surrogateTrains.timeAxis = np.arange(5000000,7000000,1)
    surrogateTrains.convolveSpikes()
    surrogateTrains.sumConvolvedSpikeTrains()
    surrogateTrains.MuaDetector()
    surrogate_ephys = Recordings.ephys(surrogateTrains,rec.LFPs)
    surrogate_ephys.coincidence('s')
    surrogate_ephys.MUA()
    surrogate_ephys.sequencing()
    sq_stack.append(surrogate_ephys.sequence_1st_spike)

NameError: name 'signale' is not defined

In [7]:
### Saving the generated sequences!
pkl.dump(sq_stack, open("surrogate2.sqn", 'wb'), pkl.HIGHEST_PROTOCOL)

In [8]:
### Sequencing recording data
rec.coincidence('s')
rec.MUA()
rec.sequencing()

NameError: name 'rec' is not defined

In [9]:
surrogate_ephys.coincidence('s')
surrogate_ephys.MUA()
surrogate_ephys.sequencing()
txt_name = 'surrogate'
writer_1st = open(txt_name + "_1st.txt",'a')
writer_median = open(txt_name + "_median.txt",'a')
tags = surrogate_ephys.spikes.tags
writer_1st.write("Unit dictionary for %s \n"%txt_name)
writer_median.write("Unit dictionary for %s \n"%txt_name)
for item in tags:
    writer_1st.write(" Unit %s ==> %s \n"%(item,tags[item]['file']))
    writer_median.write(" Unit %s ==> %s \n"%(item,tags[item]['file']))
 
for item in surrogate_ephys.sequence_1st_spike:
     writer_1st.write("%s \n"%item[:,0])
for item in surrogate_ephys.sequence_median:
    writer_median.write("%s \n"%item[:,0])
writer_1st.close()
writer_median.close()

NameError: name 'surrogate_ephys' is not defined

In [10]:
### Creating a list of sequences (Just time ordered unit id's) from surrogate data!
ssq = np.array([])
for i in range(100):
    for item in sq_stack[i]:
        ssq = np.append(ssq,np.int0(item[:,0]))
        ssq = np.append(ssq,-1)

IndexError: list index out of range

In [11]:
### Creating a list of sequences (Just time ordered unit id's) from recorded data!
rsq = np.array([])
for item in rec.sequence_1st_spike:
    rsq = np.append(rsq,np.int0(item[:,0]))
    rsq = np.append(rsq,-1)


NameError: name 'rec' is not defined

In [12]:
##Plotting sequence length distributions...
lengths = [np.diff(np.where(rsq == -1))[0],np.diff(np.where(ssq == -1))[0]]
pl.hist(lengths,30,normed=1, histtype='bar',
                            color=['blue', 'burlywood'],
                            label=['DATA', 'Simulation'],log= True);
pl.legend()

ValueError: color kwarg must have one color per dataset

In [ ]:
### Creating a list of all sequences in experiment
seq = [] 
for item in rec.sequence_1st_spike:
        seq.append(np.int0(item[:,0]))
seq = np.array(seq)
### making a set out of sequences
seq_st = [seq[0]]   # Set of sequnces found in recorded data
for ii in range(len(seq)):
    for jj in range(len(seq_st)):
        if not np.array_equal(seq[ii],seq_st[jj]) :
            seq_st.append(seq[ii])

In [599]:
### Repititions in recorded data
r_seq_rpt = []
for jtem in seq_st:
    counter = 0
    sss = 0
    for item in rec.sequence_1st_spike:
        if np.int0(item[:,0]).size >= jtem.size:
            sss += 1
        subseq = subsequence(jtem,np.int0(item[:,0]))
        if subseq[-1] and np.prod(np.clip(np.diff(subseq[0]),0,50)):
            #print subseq[0]
            counter += 1
    r_seq_rpt.append(counter)
pl.plot(np.float_(r_seq_rpt) / sss)

In [589]:
### Repititions in surrogate data
s_seq_rpt = 0
for ii in range(100):
    for item in sq_stack[ii]:
        subseq = subsequence(seq,np.int0(item[:,0]))
        if subseq[-1] and np.prod(np.clip(np.diff(subseq[0]),0,50)):
            print subseq[0]
            s_seq_rpt += 1


In [41]:
### Repititions in shuffled surrogate data
s_seq_rpt = 0
for ii in range(100):
    for item in sq_stack[ii]:
        subseq = subsequence(seq,np.int0(item[:,0]))
        if subseq[-1] and np.prod(np.clip(np.diff(subseq[0]),0,50)):
            print subseq[0]
            s_seq_rpt += 1

In [585]:
#### Determining number of sequences above certain length
sss = 0
rss = 0
for ii in range(100):
    for item in sq_stack[ii]:
        if np.int0(item[:,0]).size > 3:
            sss += 1
for item in rec.sequence_1st_spike:
    if np.int0(item[:,0]).size > 5:
        rss +=1
print rss
print sss

AttributeError: ephys instance has no attribute 'sequence_1st_spike'

In [228]:
(s_seq_rpt / float(sss))/(r_seq_rpt / float(rss))

0.11371220155720531

In [577]:
#### Shuffling the sequences
ssq_shuflled = np.split(ssq,np.where(ssq == -1)[0])
for ii in range(len(ssq_shuflled)):
    ssq_shuflled[ii] = ssq_shuflled[ii][ssq_shuflled[ii] > 0]
    np.random.shuffle(ssq_shuflled[ii])

In [293]:
fig = pl.figure()
ax = fig.add_subplot(111)
ind = range(0,len(seq),15)
names = []
for item in seq:
    names.append(str(item[:]))
xtickNames = ax.set_xticklabels(names)
ax.plot(r_seq_rpt)
pl.setp(xtickNames, rotation=45, fontsize=9)

[None, None, None, None, None, None, None, None, None, None, None, None]

In [1]:
seq.shape

NameError: name 'seq' is not defined

In [482]:
np.array(seq_st)[[4,26,116,168,65,273,336]]

array([array([2, 5]), array([5, 2]), array([ 2, 11]), array([ 2, 13]),
       array([2, 3]), array([11,  2]), array([ 2, 20])], dtype=object)

In [485]:
print seq_st[33]
r_seq_rpt[33]

[ 5  2 13 14]


12

In [498]:
for ii in range(len(rates)):
    print '%d ---> %f' %(ii,rates[ii][-1].mean())

0 ---> 0.496727
1 ---> 0.265525
2 ---> 28.867760
3 ---> 0.705521
4 ---> 0.477855
5 ---> 11.403646
6 ---> 0.050121
7 ---> 0.102287
8 ---> 0.095692
9 ---> 0.046304
10 ---> 0.122784
11 ---> 2.754287
12 ---> 0.210903
13 ---> 1.424993
14 ---> 0.604144
15 ---> 0.216628
16 ---> 0.070750
17 ---> 0.325051
18 ---> 0.088039
19 ---> 0.109361
20 ---> 0.756371
21 ---> 1.095268
22 ---> 0.409518


array([ 15.,   5.,  12.,   2.,  13.])