In [1]:
%matplotlib 
%load_ext autoreload
%autoreload 2

Using matplotlib backend: Qt4Agg


In [2]:
import sys
sys.path.append('/mnt/Data/Workspaces/Eclipse/dataAnalysis/Sleep-current/src/')

In [3]:
import matplotlib as mpl
import matplotlib.pyplot as pl
import numpy as np
import pandas as pd
import scipy.signal as scsig
import spectrum as sp
import signale
import cPickle as pkl
import time
import statsmodels.api as sm
import colormaps as cm
import seaborn as sns
import signale.tools as tools
import os

/home/chenani/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py:1350: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
/home/chenani/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))


In [4]:
def whitenARMA(sig,AR=2,MA=0):
        arma = sm.tsa.ARMA(sig, (AR,MA)).fit(disp=0)
        print 'ARMA parameters calculated for order(%s,%s)' %(AR,MA)
        return arma.resid
def MA(array,ord=2):
    ma = np.array([array[ii-ord/2:ii+ord/2].mean() for ii in range(array.size) if ii >= ord ],dtype=float)
    ma = np.insert(ma,0,array[0:ord/2])
    ma = np.append(ma,array[-(ord/2)-1:-1])
    return ma
def zScore(array):
    return(array - np.average(array))/ np.std(array)

In [5]:
animalPath = '/home/chenani/dataWork/ali/MECLesion_SleepData/Marta/Rat3661/LinearTrack_03-03-15Day1/'
localPath = '/mnt/Data/ephysdata/Rats/'

In [7]:
lfpPaths = []
for lfp in tools.locate('*-p*.lfp',animalPath):
    lfpPaths.append(os.path.join(lfp[0],lfp[1]))
lfpPaths = sorted(lfpPaths)
#lfpPaths = [ path for path in lfpPaths if (path.find('leep')>0 and path.find('CSC4')>0) ]
lfpPaths,len(lfpPaths)

(['/home/chenani/dataWork/ali/MECLesion_SleepData/Marta/Rat3661/LinearTrack_03-03-15Day1/01-2015-03-03_11-33-58/CSC06-pre.lfp',
  '/home/chenani/dataWork/ali/MECLesion_SleepData/Marta/Rat3661/LinearTrack_03-03-15Day1/03-2015-03-03_12-40-50/CSC06-post.lfp'],
 2)

In [16]:
-

In [11]:
for item in lfpPaths[:1]:
    lfp = pkl.load(open(item,'rb'))
    Pxx, freqs, t = lfp.spectrogram(minFreq=.1,maxFreq=200,overlap=1,windowSize=2048,whiten=True)
#print freqs[50:,0]
Dspg = Pxx[:7,:]
Tspg = Pxx[8:15,:]
Gspg = Pxx[17:30,:]
FGspg = Pxx[130:215,:]
Rspg = Pxx[260:300,:]
Dp = Dspg.mean(axis=0)
Tp = Tspg.mean(axis=0)
Gp = Gspg.mean(axis=0)
FGp = FGspg.mean(axis=0)
Rp = Rspg.mean(axis=0)

In [15]:
pl.scatter(t[0,:]/1e3,y_pred)

In [12]:
X = np.array([Dp,Tp,Gp,FGp,Rp]).T
from sklearn.cluster import KMeans
y_pred = KMeans(n_clusters=3).fit_predict(X)

In [14]:
pl.scatter(X[:,0],X[:,1],c=y_pred)

In [59]:
pl.plot(zScore(Dp))
pl.plot(zScore(Tp),label='Tp')
pl.plot(zScore(Rp))
pl.legend()

In [47]:
freqs[260:300,0]

array([ 172.81054688,  173.47265625,  174.13476563,  174.796875  ,
        175.45898438,  176.12109375,  176.78320313,  177.4453125 ,
        178.10742188,  178.76953125,  179.43164063,  180.09375   ,
        180.75585938,  181.41796875,  182.08007813,  182.7421875 ,
        183.40429688,  184.06640625,  184.72851563,  185.390625  ,
        186.05273438,  186.71484375,  187.37695313,  188.0390625 ,
        188.70117188,  189.36328125,  190.02539063,  190.6875    ,
        191.34960938,  192.01171875,  192.67382813,  193.3359375 ,
        193.99804688,  194.66015625,  195.32226563,  195.984375  ,
        196.64648438,  197.30859375,  197.97070313,  198.6328125 ])

In [38]:
SleepEpochsEven = pd.DataFrame([[1,30,'SWS','sleep01','2013-05-31','R616'],
                            [31,45,'REM','sleep01','2013-05-31','R616'],
                            [45,55,'SWS','sleep01','2013-05-31','R616'],
                            [68,90,'SWS','sleep01','2013-05-31','R616'],
                            [95,115,'REM','sleep01','2013-05-31','R616'],
                            [120,135,'SWS','sleep01','2013-05-31','R616'],
                            [145,185,'SWS','sleep01','2013-05-31','R616'],
                            [190,215,'REM','sleep01','2013-05-31','R616'],
                            [218,232,'SWS','sleep01','2013-05-31','R616'],
                            [233,260,'REM','sleep01','2013-05-31','R616'],
                            [261,295,'SWS','sleep01','2013-05-31','R616'],
                            [300,330,'REM','sleep01','2013-05-31','R616'],
                            [330,360,'SWS','sleep01','2013-05-31','R616'],
                            [361,402,'REM','sleep01','2013-05-31','R616'],
                            [403,415,'SWS','sleep01','2013-05-31','R616'],
                            [430,485,'SWS','sleep01','2013-05-31','R616'],
                            [485,505,'REM','sleep01','2013-05-31','R616'],
                            [0,270,'REM','sleep02','2013-05-31','R616'],
                            [271,335,'SWS','sleep02','2013-05-31','R616'],
                            [271,335,'SWS','sleep02','2013-05-31','R616'],
                            ],
                           columns=['t0','t1','epoch','session','date','animal'])


In [33]:
psd = np.array([])
dates = []
sessions = []
animals = []
state = []
freqz = []
epN = 0
epochNo = []
for path in lfpPaths[:]:
    pickedChannel = pkl.load(open(path,'rb'))
    NFFT = int(2 ** 17)
    expDate = path.split('_')[0].split('/')[-1]
    session = path.split('_')[-2]
    session = session[:-1]+'0'+session[-1]
    relevantEpochs = SleepEpochsEven[np.logical_and(SleepEpochsEven['date']== expDate,
                                                SleepEpochsEven['session']==session)]
    relevantEpochs.index = range(relevantEpochs.index.size)
    Nepochs = relevantEpochs.shape[0]
    print expDate,session
    if Nepochs:
        print Nepochs
        print relevantEpochs
        for kk in range(Nepochs):
            t0 = relevantEpochs.t0[kk]
            tf = relevantEpochs.t1[kk]
            sigSlice = np.logical_and(pickedChannel.time_axis()>t0*1e3,pickedChannel.time_axis()<tf*1e3)
            dsig = scsig.decimate(pickedChannel.signal[sigSlice],2)
            arma = sm.tsa.ARMA(dsig,(2,0)).fit(disp=0)
            residPSD = sp.Periodogram(arma.resid,sampling=1000,NFFT=NFFT)
            residPSD()
            Nfreqz = residPSD.psd.size
            smoothingKernel = scsig.gaussian(Nfreqz/100,Nfreqz/200)
            residPSDSmooth = np.convolve(residPSD.psd,smoothingKernel,'same')
            residPSDSmooth = scsig.decimate(residPSDSmooth,10)
            psd = np.append(psd,residPSDSmooth)
            freqz.append(scsig.decimate(residPSD.frequencies(),10))
            dates.append(residPSDSmooth.size*[relevantEpochs.date[0]])
            sessions.append(residPSDSmooth.size*[relevantEpochs.session[0]])
            animals.append(residPSDSmooth.size*[relevantEpochs.animal[0]])
            state.append(residPSDSmooth.size*[relevantEpochs.epoch[kk]])
            epochNo.append(residPSDSmooth.size*[epN])
            epN+=1
animals = np.array(animals).flatten()
dates = np.array(dates).flatten()
sessions = np.array(sessions).flatten()
state = np.array(state).flatten()
freqz = np.array(freqz).flatten()
epochNo = np.array(epochNo).flatten()
dfm = np.array([psd,freqz,state,epochNo,sessions,dates,animals]).T
df = pd.DataFrame(dfm,columns=['psd','f','epoch','epochNo','session','date','animal'])
df[['psd', 'f']] = df[['psd', 'f']].astype(float)
df[['epochNo']] = df[['epochNo']].astype(int)
df[['epoch','session','date','animal']] = df[['epoch','session','date','animal']].astype(str)

MECLesion /home/chenani/dataWork/ali/MECLesio0n
MECLesion /home/chenani/dataWork/ali/MECLesio0n


In [34]:
freqBins = np.linspace(0.5,300.5,600)
psd = np.array([])
dates = []
sessions = []
animals = []
state = []
freqz = []
epN = 0
epochNo = []
for path in lfpPaths[:]:
    pickedChannel = pkl.load(open(path,'rb'))
    expDate = path.split('_')[0].split('/')[-1]
    session = path.split('_')[-2]
    session = session[:-1]+'0'+session[-1]
    relevantEpochs = SleepEpochs[np.logical_and(SleepEpochs['date']== expDate,
                                                SleepEpochs['session']==session)]
    relevantEpochs.index = range(relevantEpochs.index.size)
    Nepochs = relevantEpochs.shape[0]
    print expDate,session
    if Nepochs:
        #print Nepochs
        #print relevantEpochs
        for kk in range(Nepochs):
            t0 = relevantEpochs.t0[kk]
            tf = relevantEpochs.t1[kk]
            sigSlice = np.logical_and(pickedChannel.time_axis()>t0*1e3,pickedChannel.time_axis()<tf*1e3)
            dsig = scsig.decimate(pickedChannel.signal[sigSlice],2)
            NFFT = int(2**(np.floor(np.log2(dsig.size))+1))
            arma = sm.tsa.ARMA(dsig,(2,0)).fit(disp=0)
            residPSD = sp.Periodogram(arma.resid,sampling=1000,NFFT=NFFT)
            residPSD()
            Nfreqz = residPSD.psd.size
            hst,freqBins = np.histogram(residPSD.frequencies(),bins=freqBins)
            avgPSD = np.zeros(hst.size)
            idx = 0
            for ii,item in enumerate(hst):
                avgPSD[ii] = residPSD.psd[idx:idx+item].mean()
                idx+=item
            Imax = avgPSD.argmax()
            avgPSD[Imax] = (avgPSD[Imax-1] + avgPSD[Imax+1])/2.0
            #avgPSD = np.convolve(avgPSD,scsig.gaussian(freqBins.size/30,freqBins.size/60),'same')
            psd = np.append(psd,avgPSD)
            freqz.append(np.arange(1,300.5,0.5))
            dates.append(avgPSD.size*[relevantEpochs.date[0]])
            sessions.append(avgPSD.size*[relevantEpochs.session[0]])
            animals.append(avgPSD.size*[relevantEpochs.animal[0]])
            state.append(avgPSD.size*[relevantEpochs.epoch[kk]])
            epochNo.append(avgPSD.size*[epN])
            epN+=1
animals = np.array(animals).flatten()
dates = np.array(dates).flatten()
sessions = np.array(sessions).flatten()
state = np.array(state).flatten()
freqz = np.array(freqz).flatten()
epochNo = np.array(epochNo).flatten()
dfm = np.array([psd,freqz,state,epochNo,sessions,dates,animals]).T
df = pd.DataFrame(dfm,columns=['psd','f','epoch','epochNo','session','date','animal'])
df[['psd', 'f']] = df[['psd', 'f']].astype(float)
df[['epochNo']] = df[['epochNo']].astype(int)
df[['epoch','session','date','animal']] = df[['epoch','session','date','animal']].astype(str)

MECLesion /home/chenani/dataWork/ali/MECLesio0n
MECLesion /home/chenani/dataWork/ali/MECLesio0n


In [35]:
pl.yscale('log')
sns.tsplot(value='psd',time='f',condition='epoch',unit='epochNo',data=df)#[df['epoch']=='SWS'])
pl.xlim(0,250)

/home/chenani/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py:892: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))


UnboundLocalError: local variable 'x' referenced before assignment

In [106]:
df.to_pickle(localPath+'psdDataavg.pd')
#SleepEpochsEven.to_pickle(localPath+'SleepEpochsEven.pd')

In [32]:
(SleepEpochsEven[SleepEpochsEven['epoch']=='REM']['t1']-SleepEpochsEven[SleepEpochsEven['epoch']=='REM']['t0']).hist(bins=40)
(SleepEpochsEven[SleepEpochsEven['epoch']=='SWS']['t1']-SleepEpochsEven[SleepEpochsEven['epoch']=='SWS']['t0']).hist(bins=40,alpha=0.5)
pl.show()

In [25]:
SleepEpochsEven[(SleepEpochsEven.t1 - SleepEpochsEven.t0) >100]

t0    t1 epoch  session        date animal
84  550   660   SWS  sleep03  2011-09-23     G6
92  980  1130   SWS  sleep03  2011-09-23     G6

In [94]:
psd.size,freqz.size,state.size,epochNo.size,sessions.size,dates.size,animals.size

(1569, 1497, 1569, 1569, 1569, 1569, 1569)

In [66]:
freqBins

array([   0.,   50.,  100.,  150.,  200.,  250.,  300.,  350.,  400.,
        450.,  500.])

'2011-08-04'

In [93]:
relevantEpochs.index = range(relevantEpochs.index.size)

In [15]:
s = lfpPaths[0].split('_')[-2]

In [21]:
s[:-1]+'0'+s[-1]

'sleep01'

In [69]:
freqBins = np.linspace(0.5,255.5,255)

In [90]:
np.arange(1,250.5,0.5).size,freqBins.size

(499, 500)

In [70]:
np.histogram(residPSD.frequencies(),bins=freqBins)

(array([132, 131, 132, 131, 132, 132, 131, 132, 131, 132, 132, 131, 132,
        131, 132, 131, 132, 132, 131, 132, 131, 132, 132, 131, 132, 131,
        132, 132, 131, 132, 131, 132, 131, 132, 132, 131, 132, 131, 132,
        132, 131, 132, 131, 132, 131, 132, 132, 131, 132, 131, 132, 132,
        131, 132, 131, 132, 132, 131, 132, 131, 132, 131, 132, 132, 131,
        132, 131, 132, 132, 131, 132, 131, 132, 132, 131, 132, 131, 132,
        131, 132, 132, 131, 132, 131, 132, 132, 131, 132, 131, 132, 132,
        131, 132, 131, 132, 131, 132, 132, 131, 132, 131, 132, 132, 131,
        132, 131, 132, 132, 131, 132, 131, 132, 131, 132, 132, 131, 132,
        131, 132, 132, 131, 132, 131, 132, 132, 131, 132, 131, 132, 131,
        132, 132, 131, 132, 131, 132, 132, 131, 132, 131, 132, 132, 131,
        132, 131, 132, 131, 132, 132, 131, 132, 131, 132, 132, 131, 132,
        131, 132, 132, 131, 132, 131, 132, 131, 132, 132, 131, 132, 131,
        132, 132, 131, 132, 131, 132, 132, 131, 132

In [83]:
np.linspace(0.01,250,500)

array([  1.00000000e-02,   5.10981964e-01,   1.01196393e+00,
         1.51294589e+00,   2.01392786e+00,   2.51490982e+00,
         3.01589178e+00,   3.51687375e+00,   4.01785571e+00,
         4.51883768e+00,   5.01981964e+00,   5.52080160e+00,
         6.02178357e+00,   6.52276553e+00,   7.02374749e+00,
         7.52472946e+00,   8.02571142e+00,   8.52669339e+00,
         9.02767535e+00,   9.52865731e+00,   1.00296393e+01,
         1.05306212e+01,   1.10316032e+01,   1.15325852e+01,
         1.20335671e+01,   1.25345491e+01,   1.30355311e+01,
         1.35365130e+01,   1.40374950e+01,   1.45384770e+01,
         1.50394589e+01,   1.55404409e+01,   1.60414228e+01,
         1.65424048e+01,   1.70433868e+01,   1.75443687e+01,
         1.80453507e+01,   1.85463327e+01,   1.90473146e+01,
         1.95482966e+01,   2.00492786e+01,   2.05502605e+01,
         2.10512425e+01,   2.15522244e+01,   2.20532064e+01,
         2.25541884e+01,   2.30551703e+01,   2.35561523e+01,
         2.40571343e+01,

In [14]:
for path in lfpPaths:
    try :
        pkl.load(open(path,'rb'))
        #print path
        #print 'passed!!!'
    except EOFError:
        print 'Shit'
        print path
        print 'Shit'

Shit
/mnt/Data/ephysdata/Gerbils/G5/2011-08-07_sleep1_csc4.lfp
Shit
Shit
/mnt/Data/ephysdata/Gerbils/G5/2011-08-07_sleep2_csc4.lfp
Shit


In [15]:
import shutil
shutil.copy2('/home/chenani/dataWork/ali/Gerbils/gerbil5/2011-08-07/')